/**************************************************************************************
Exclusion of Liability for this demo software:
  The following software is intended for and must only be used for reference and in an
  evaluation laboratory environment. It is provided without charge and is subject to
  alterations. There is no warranty for the software, to the extent permitted by
  applicable law. Except when otherwise stated in writing the copyright holders and/or
  other parties provide the software "as is" without warranty of any kind, either
  expressed or implied.
  Please refer to the Agreement in README_DISCLAIMER.txt, provided together with this file!
  By installing or otherwise using the software, you accept the terms of this Agreement.
  If you do not agree to the terms of this Agreement, then do not install or use the
  Software!
**************************************************************************************/

/**************************************************************************************

Copyright (c) Hilscher Gesellschaft fuer Systemautomation mbH. All Rights Reserved.

***************************************************************************************/

#ifndef COMPONENTS_CIFXAPPLICATIONDEMOPNS_INCLUDES_APPPNS_DEMOAPPLICATION_H_
#define COMPONENTS_CIFXAPPLICATIONDEMOPNS_INCLUDES_APPPNS_DEMOAPPLICATION_H_

#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#include "AppPNS_DemoApplication_Config.h"

#include "App_DemoApplication.h"
#include "App_PacketCommunication.h"
#include "App_SystemPackets.h"

#include "Hil_ApplicationCmd.h"
#include "Hil_SystemCmd.h"
#include "Hil_Results.h"
#include "Hil_Packet.h"
#include "Hil_DualPortMemory.h"
#include "Hil_ComponentID.h"
#include "Hil_DeviceProductionData.h"
#include "pns_firmware_version.h"

#include "PNSIF_API.h"

/*************************************************************************************/

#define TX_TIMEOUT       500 /* milliseconds */
#define TXRX_TIMEOUT     500 /* milliseconds */

#define APPPNS_PROCESS_DATA_INPUT_SIZE        6
#define APPPNS_PROCESS_DATA_OUTPUT_SIZE       10

/*************************************************************************************/

typedef struct PROTOCOL_IDENTIFICATION_Ttag
{
  const char* szFirmwareName;
  const uint16_t usFirmwareMajor;
  const uint16_t usFirmwareMinor;
} PROTOCOL_IDENTIFICATION_T;

/*************************************************************************************/
/*************************************************************************************/

typedef struct MY_PNS_COMM_CHANNEL_HANDLER_RSC_Ttag
{
  CIFXHANDLE              hCifXChannel;
  CHANNEL_INFORMATION     *ptCifXChannelInfo;

  PKT_INTERFACE_H         hPktIfRsc;
  CIFX_PACKET             tPacket;

  uint8_t abActorData[APPPNS_PROCESS_DATA_INPUT_SIZE];   /* Control data produced by Master, to control device peripherals (e.g. LEDs) */
  uint8_t abSensorData[APPPNS_PROCESS_DATA_OUTPUT_SIZE]; /* Status data for the Master, generated by the device peripherals (e.g. Temperature)*/

} MY_PNS_COMM_CHANNEL_HANDLER_RSC_T;

/*************************************************************************************/

extern PROTOCOL_IDENTIFICATION_T g_tProtocolIdentification;

/*************************************************************************************/

long SetConfigParams( void* pvPck, uint16_t usDeviceClass );
long SetModulConfig( void* pvPck );

bool     AppPNS_PacketHandler( void *pvUserData, CIFX_PACKET *ptPacket );
uint32_t AppPNS_ConfigureStack( MY_PNS_COMM_CHANNEL_HANDLER_RSC_T *ptRsc );
uint32_t AppPNS_SetOemData(MY_PNS_COMM_CHANNEL_HANDLER_RSC_T *ptRsc);
uint32_t AppPNS_ActivateDdp(MY_PNS_COMM_CHANNEL_HANDLER_RSC_T *ptRsc);
uint32_t AppPNS_SetMacAddress( MY_PNS_COMM_CHANNEL_HANDLER_RSC_T *ptRsc );


#endif /* COMPONENTS_CIFXAPPLICATIONDEMOPNS_INCLUDES_APPPNS_DEMOAPPLICATION_H_ */
